plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.actuator

    testImplementation libs.spring.boot.starter.test
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
