plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.spotless)
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.actuator
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.validation
    implementation libs.flyway.core
    implementation libs.flyway.database.postgresql
    implementation libs.jjwt.api
    runtimeOnly libs.postgresql
    runtimeOnly libs.jjwt.impl
    runtimeOnly libs.jjwt.jackson
    testImplementation libs.spring.boot.starter.test
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly libs.h2
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

spotless {
    java {
        googleJavaFormat()
    }
}
