spring.datasource.url=jdbc:postgresql://localhost:5432/retirement_modeler
spring.datasource.username=retirement_modeler
spring.datasource.password=retirement_modeler
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
